#!/usr/bin/env ruby

# 'brew tap'
tap "homebrew/cask"
tap "homebrew/cask-fonts"

brew "terminal-notifier"
brew "trash"
brew "mas"
cask "iterm2"
cask "flux"
cask "amethyst"

cask "font-alegreya"
cask "font-alegreya-sans"
cask "font-anonymous-pro"
cask "font-cardo"
cask "font-cormorant"
cask "font-fira-code"
cask "font-fira-mono"
cask "font-fira-sans"
cask "font-hack-nerd-font"
cask "font-hasklig"
cask "font-inconsolata"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"
cask "font-lato"
cask "font-monoid"
# cask "font-open-sans"
# cask "font-source-code-pro"
# cask "font-source-sans-pro"
# cask "font-source-serif-pro"
cask "font-vollkorn"
