---
- hosts: all
  vars:
    home: "{{ lookup('env','HOME') }}"
    code_home: "{{ home }}/code"
    vendor_code:  "{{ code_home }}/vendor"
    # applications: # .dmg, .app, .zip type applications via brew-cask
    #   - google-chrome
    #   - firefox

  tasks:
    - homebrew_tap: tap=homebrew/versions state=present
    - homebrew_tap: tap=caskroom/fonts state=present
    - homebrew_tap: tap=osx-cross/avr state=present
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        # - caskroom/cask/brew-cask
        # - apple-gcc42
        # - vim
        - git
        - trash
        # - caskroom/cask/osxfuse
        # - sshfs
        # - rbenv
        # - ruby-build
        # - elasticsearch
        # - postgres
        # - mysql
        # - apache-spark
        # - rust
        - planck

    #State : STANDARD.
    # - name: Emacs
    #   homebrew: name=emacs state=present install_options=with-cocoa,with-glib,with-gnutls,HEAD

    - name: Install homebrew cask apps
      homebrew_cask: name={{ item }} state=present
      with_items:
#        - google-chrome
        - amethyst
        # - quicksilver
        - diffmerge
#        - intellij-idea
        - iterm2
        - flux
        # - istat-menus
        # - menumeters
        - launchrocket
        - trailer
        # - sequel-pro
        # - telegram
        # - vlc
        # - spotify
        # - skype
        # - elm-platform
        # - karabiner
        # - seil
        - font-anonymous-pro
        - font-source-code-pro
        - font-alegreya
        - font-alegreya-sans
        - font-cardo
        # - font-droid-sans-mono
        # - font-droid-sans
        # - font-droid-serif
        - font-fira-code
        - font-fira-mono
        - font-fira-sans
        - font-hasklig
        - font-inconsolata
        - font-lato
        - font-monoid
        - font-open-sans
        - font-vollkorn


    - name: Clone dotfiles
      # I set force and update to no so that if I have any working
      # changes or changes that I haven't pushed up it doesn't reset
      # my local history.
      git: repo=git@github.com:minimal/{{ item }}.git dest={{ code_home }}/{{ item }} force=no update=no recursive=yes accept_hostkey=true
      with_items:
        - dotfiles
        - prezto

    - name: Symlink dotfiles
      file: path={{ home }}/{{ item }} src={{ code_home }}/dotfiles/{{ item }} state=link
      with_items:
        # - .gitconfig
        # - .tmux.conf
        - .amethyst
        - .sshrc
        # - .lein
        - .ansible

    - name: Symlink dotfiles2
      file: path={{ home }}/.{{ item }} src={{ code_home }}/dotfiles/{{ item }} state=link
      with_items:
        # - gitignore
        - boot
        - joker
        - emacs.d

    - name: Symlink dotfiles3
      file: path={{ home }}/.config/{{ item }} src={{ code_home }}/dotfiles/{{ item }} state=link
      with_items:
        - nixpkgs

    - name: Setup prezto # TODO: the symlinks as well
      file: path={{ home }}/.zprezto src={{ code_home }}/prezto state=link

    - name: make cache dir
      file: path={{ home }}/.cache state=directory
