---
- hosts: all
  vars:
    home: "{{ lookup('env','HOME') }}"
    code_home: "{{ home }}/code"
    vendor_code:  "{{ code_home }}/vendor"
    # applications: # .dmg, .app, .zip type applications via brew-cask
    #   - google-chrome
    #   - firefox

  tasks:
    - name: Install libraries with homebrew
      homebrew: name={{ item }} state=present
      with_items:
        - wget
        - python
        - python3
        - leiningen
        - htop
        - zsh
        - tmux
        # - caskroom/cask/brew-cask
        # - apple-gcc42
        # - vim
        - the_silver_searcher
        - git
        - coreutils
        - findutils
        - rlwrap
        - gnu-tar
        - gnu-sed
        - gawk
        - gnutls
        - gnu-indent
        - gnu-getopt
        - tree
        - aspell
        - unrar
        # - caskroom/cask/osxfuse
        - sshfs
        - fpp
        - terminal-notifier
        # - rbenv
        # - ruby-build
        # - elasticsearch
        - mysql
        - apache-spark
        - rust
        - node

    - name: Emacs
      homebrew: name=emacs state=present install_options=with-cocoa,with-glib,with-gnutls,HEAD

    - name: Install homebrew cask apps
      homebrew_cask: name={{ item }} state=present
      with_items:
        - amethyst
        - quicksilver
        - diffmerge
        - intellij-idea
        - iterm2
        # - istat-menus
        - menumeters
        # - trailer
        - sequel-pro
        - telegram
        - vlc
        # - spotify
        # - skype
        - elm-platform

    - name: Clone dotfiles
      # I set force and update to no so that if I have any working
      # changes or changes that I haven't pushed up it doesn't reset
      # my local history.
      git: repo=git@github.com:minimal/{{ item }}.git dest={{ code_home }}/{{ item }} force=no update=no recursive=yes
      with_items:
        - dotfiles
        - prezto

    - name: Symlink dotfiles
      file: path={{ home }}/{{ item }} src={{ code_home }}/dotfiles/{{ item }} state=link
      with_items:
        - .gitconfig
        - .tmux.conf
        - .amethyst
        - .sshrc
        - .tmux.conf
        - .lein
        - .ansible
        - .emacs.d

    - name: Symlink dotfiles2
      file: path={{ home }}/.{{ item }} src={{ code_home }}/dotfiles/{{ item }} state=link
      with_items:
        - gitignore
        - nixpkgs

    - name: Setup prezto # TODO: the symlinks as well
      file: path={{ home }}/.zprezto src={{ code_home }}/prezto state=link

    - name: Pip python packages
      environment:
        PIP_REQUIRE_VIRTUALENV: false
      pip: name={{ item }}
      with_items:
        - virtualenv
        - virtualenvwrapper
        - flake8
        - ipython

    - name: Check if ls++ is installed
      stat: path={{ home }}/perl5/bin/ls++
      register: lspp_installed

    - name: Get ls++
      git: repo=git@github.com:trapd00r/ls--.git dest={{ vendor_code }}/ls--

    - name: Install ls++
      shell: cd {{ vendor_code }}/ls-- &&  cpan Term::ExtendedColor && perl Makefile.PL && make && make install && cp ls++.conf {{ home }}/.ls++.conf
      when: lspp_installed.stat.exists == false
