;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        cljr-slash
        cua-paste
        paredit-doublequote
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        ))

(setq mc/cmds-to-run-once
      '(
        magit-status
        ))
