;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-or-indentation
        cljr-slash
        coffee-dedent-line-backspace
        cua-paste
        dabbrev-expand
        end-of-buffer
        forward-sexp
        helm-confirm-and-exit-minibuffer
        ignore
        org-delete-char
        org-self-insert-command
        paredit-backward
        paredit-close-curly
        paredit-doublequote
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        paredit-kill
        yas-expand
        markdown-exdent-or-delete
        ))

(setq mc/cmds-to-run-once
      '(
        cua-toggle-rectangle-mark
        describe-key-briefly
        helm-M-x
        helm-maybe-exit-minibuffer
        helm-mini
        helm-swoop
        idris-load-file
        mac-mwheel-scroll
        magit-status
        mouse-set-region
        ))
