;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        beginning-of-line-or-indentation
        cljr-slash
        coffee-dedent-line-backspace
        cua-paste
        helm-confirm-and-exit-minibuffer
        org-self-insert-command
        paredit-doublequote
        paredit-forward
        paredit-forward-barf-sexp
        paredit-forward-delete
        paredit-forward-kill-word
        paredit-forward-slurp-sexp
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        helm-M-x
        helm-maybe-exit-minibuffer
        magit-status
        ))
