# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          # Shallow clones won't work
          fetch-depth: 0
      - uses: cachix/install-nix-action@v13
        env:
          NIX_VERSION: nix-2.4pre20210823_af94b54
        with:
          install_url: https://github.com/numtide/nix-unstable-installer/releases/download/${{ env.NIX_VERSION }}/install
          extra_nix_config: |
            experimental-features = nix-command flakes
      - name: Run Flake Checks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          nix flake check -v --show-trace
      - name: Run linux home manager build
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: |
          nix develop -c home-manager build --flake '.#DESKTOP-096IFDV'
      - name: Run linux home manager build
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          nix develop -c home-manager build --flake '.#MacBook-Prolocal'
        timeout-minutes: 240
